[package]
name = "giztoy-kv"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
redb = "2"
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
