[package]
name = "giztoy-speech"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Interfaces for voice and speech processing (TTS/ASR)"

[dependencies]
giztoy-audio = { workspace = true }
giztoy-trie = { workspace = true }

async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
