[book]
title = "Giztoy Documentation"
authors = ["Haivivi Team"]
language = "en"
multilingual = false
src = "../../docs/en"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/haivivi/giztoy"
git-repository-icon = "fa-github"
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js", "lang-switch.js"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
use-hierarchical = true
