[package]
name = "giztoy-onnx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Rust bindings for ONNX Runtime C API"

[dependencies]
thiserror = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "onnx_bench"
harness = false
